/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xisysgroup.dbi;

import java.awt.Dimension;
import java.net.URL;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeSelectionModel;
import com.xisysgroup.dbi.variables.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author akisoft
 */
public final class Mainframe extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    DefaultComboBoxModel combomodel;
    DefaultListModel listModel;
    DefaultListModel listModel2;

    /**
     * Creates new form Mainframe
     */
    public Mainframe() {
        initComponents();
        setcombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Integrated Database System for Student Management");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 440, 181));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, 150));

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList2);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 230, 230));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jTabbedPane1.addTab("Description", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jTabbedPane1.addTab("content", jScrollPane5);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 440, 240));

        jButton1.setText("EXPORT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 90, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 80, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 80, 20));

        jLabel2.setText("Table name:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 80, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Export to"));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 440, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 550));

        jMenu1.setText("File");

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Database");

        jMenuItem1.setText("Add Database Engine");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Operation");

        jMenuItem2.setText("Integrate");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new AddDb(this, rootPaneCheckingEnabled).setVisible(true);
        setcombo();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String dbnameEng = jComboBox1.getSelectedItem().toString();
        int index = Dababase_variable.DbEngineName.indexOf(dbnameEng);
        Dababase_variable.dbnames.removeAllElements();
        new TableTypes().GetDb(Dababase_variable.DbEngineUrl.elementAt(index), Dababase_variable.DbEngineUser.elementAt(index), Dababase_variable.DbEnginePass.elementAt(index), "save", Dababase_variable.DbEngineType.elementAt(index).toLowerCase());
        listModel = new DefaultListModel();
        for (int i = 0; i < Dababase_variable.dbnames.size(); i++) {
            System.out.println("here");
            listModel.addElement(Dababase_variable.dbnames.elementAt(i));
        }
        Dababase_variable.dbnames.removeAllElements();
        jList1.setModel(listModel);
        // load dabase from engine

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String dbnameEng = jComboBox1.getSelectedItem().toString();
        Dababase_variable.DbTables.removeAllElements();
        int index = Dababase_variable.DbEngineName.indexOf(dbnameEng);
        JOptionPane.showMessageDialog(rootPane, Dababase_variable.DbEngineUrl.elementAt(index));
        String datasource = null;//"jdbc:mysql://" + Dababase_variable.DbEngineUrl.elementAt(index) + "/";
        if (Dababase_variable.DbEngineType.elementAt(index).equals("mysql")) {
            datasource = "jdbc:mysql://" + Dababase_variable.DbEngineUrl.elementAt(index) + "/";
        } else {
            datasource = "jdbc:postgresql://" + Dababase_variable.DbEngineUrl.elementAt(index) + ":5432/";
        }
        new AllTableName().GetTable(datasource, jList1.getSelectedValue().toString(), Dababase_variable.DbEngineUser.elementAt(index), Dababase_variable.DbEnginePass.elementAt(index), Dababase_variable.DbEngineType.elementAt(index));

        listModel2 = new DefaultListModel();
        for (int i = 0; i < Dababase_variable.DbTables.size(); i++) {
            listModel2.addElement(Dababase_variable.DbTables.elementAt(i));

        }
        jList2.setModel(listModel2);
        Dababase_variable.DbTables.removeAllElements();

        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        String dbnameEng = jComboBox1.getSelectedItem().toString();
        Dababase_variable.DbTablesCol.removeAllElements();
        Dababase_variable.DbTablesColDes.removeAllElements();
        int index = Dababase_variable.DbEngineName.indexOf(dbnameEng);
        JOptionPane.showMessageDialog(rootPane, Dababase_variable.DbEngineUrl.elementAt(index));
        //String datasource = "jdbc:mysql://" + Dababase_variable.DbEngineUrl.elementAt(index) + "/";
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Column Name");
        tableModel.addColumn("Column Type");
        String datasource = null;//"jdbc:mysql://" + Dababase_variable.DbEngineUrl.elementAt(index) + "/";
        if (Dababase_variable.DbEngineType.elementAt(index).equals("mysql")) {
            datasource = "jdbc:mysql://" + Dababase_variable.DbEngineUrl.elementAt(index) + "/";
        } else {
            datasource = "jdbc:postgresql://" + Dababase_variable.DbEngineUrl.elementAt(index) + ":5432/";
        }
        new ColumnNam().getColumnName(datasource, jList1.getSelectedValue().toString(), Dababase_variable.DbEngineUser.elementAt(index), Dababase_variable.DbEnginePass.elementAt(index), jList2.getSelectedValue().toString(), jTable2, Dababase_variable.DbEngineType.elementAt(index));
        for (int i = 0; i < Dababase_variable.DbTablesColDes.size(); i++) {
            Object data[] = {Dababase_variable.DbTablesCol.elementAt(i), Dababase_variable.DbTablesColDes.elementAt(i)};
            tableModel.addRow(data);
            data = null;
        }
        jTable1.setModel(tableModel);
        // TODO add your handling code here:
    }//GEN-LAST:event_jList2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new selectdbs(this, rootPaneCheckingEnabled, jTable1, jTable2).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int response = JOptionPane.showConfirmDialog(rootPane, "are you sure you want to exit");
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
// TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList3MouseClicked

    private void jList4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(jTextField1.getText().isEmpty()){
      JOptionPane.showMessageDialog(rootPane, "Enter Table Name");
      return;
      }
        export();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    void export() {
        if (jComboBox2.getSelectedIndex() == 1) {
            mysqlCreation();
        } else if (jComboBox2.getSelectedIndex() == 2) {
//postgree
            postCreation();
        }else{
        JOptionPane.showMessageDialog(rootPane,"Select export location");
        }
    }

    void mysqlCreation() {


        connect_mysql db = new connect_mysql();
        try {
            db.getConnection();
            //CREATE TABLE IN MYSQL DB
            String table = "CREATE TABLE IF NOT EXISTS ";
            table += jTextField1.getText() + " (";
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                table += jTable1.getValueAt(i, 0);
                String dtype = jTable1.getValueAt(i, 1).toString();
                if (dtype.equalsIgnoreCase("int") || dtype.equalsIgnoreCase("int4")) {
                    dtype = "int(11)";
                }
                if (dtype.equalsIgnoreCase("varchar")) {
                    dtype += "(255)";
                }

                table += " " + dtype + ",";
            }
            table = table.substring(0, table.length() - 1);
            table += ")";
            System.out.println("query " + table);
            db.ps = db.conn.prepareStatement(table);
            db.ps.execute();



            String insert = "";
            String insertvalue = "insert into ";

            insertvalue += jTextField1.getText() + "(";
            for (int i = 0; i < jTable2.getColumnCount(); i++) {
                insertvalue += jTable2.getColumnName(i) + ",";
            }
            insertvalue = insertvalue.substring(0, insertvalue.length() - 1);
            insertvalue += ")";
            System.out.println("insert " + insertvalue);
            insert = " values(";

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                insert = " values(";

                for (int j = 0; j < jTable2.getColumnCount(); j++) {
                    if(jTable2.getValueAt(i, j).toString().equals("null")){
                     insert += "'"+0+"'" + ",";
                    }else{
                     insert += "'"+jTable2.getValueAt(i, j)+"'" + ",";
                    }
                   

                }
                insert = insert.substring(0, insert.length() - 1);
                if (insert.endsWith(",")) {
                    insert += "0";
                }
                insert += ")";
                System.out.println(insertvalue+" " +insert);
                db.ps = db.conn.prepareStatement(insertvalue+" "+ insert);

                db.ps.execute();

            }
            JOptionPane.showMessageDialog(null, "table Exported to MySQL Database Server");

        } catch (Exception e) {
           JOptionPane.showMessageDialog(rootPane, "Data not Export \nTable probably exist\nTry a new name");
            e.printStackTrace();
        }

    }

    void postCreation() {
        connect_mysql db = new connect_mysql();
        try {
            db.postConnection();
            //CREATE TABLE IN POSTGRES DB
            String table = "CREATE TABLE ";
            table += jTextField1.getText() + " (";
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                table += jTable1.getValueAt(i, 0);
                String dtype = jTable1.getValueAt(i, 1).toString();
                if (dtype.equalsIgnoreCase("int") || dtype.equalsIgnoreCase("int4")) {
                    dtype = "int";
                }
                if (dtype.equalsIgnoreCase("TINYINT")) {
                    dtype = "int4";
                }
                if (dtype.equalsIgnoreCase("varchar(255)")) {
                    dtype = "varchar";
                }

                table += " " + dtype + " ,";
            }
            table = table.substring(0, table.length() - 1);
            table += ")";
            System.out.println("query " + table);
            db.ps = db.conn.prepareStatement(table);
            db.ps.execute();


            String insert = "";
            String insertvalue = "insert into ";

            insertvalue += jTextField1.getText() + "(";
            for (int i = 0; i < jTable2.getColumnCount(); i++) {
                insertvalue += jTable2.getColumnName(i) + ",";
            }
            insertvalue = insertvalue.substring(0, insertvalue.length() - 1);
            insertvalue += ")";
            System.out.println("insert " + insertvalue);
            insert = " values(";

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                insert = " values(";

                for (int j = 0; j < jTable2.getColumnCount(); j++) {
                   if(jTable2.getValueAt(i, j).toString().equals("null")){
                     insert += "'"+0+"'" + ",";
                    }else{
                     insert += "'"+jTable2.getValueAt(i, j)+"'" + ",";
                    }

                }
                insert = insert.substring(0, insert.length() - 1);
                if (insert.endsWith(",")) {
                    insert += "0";
                }
                insert += ")";
                System.out.println(insertvalue+" " +insert);
                db.ps = db.conn.prepareStatement(insertvalue+" "+ insert);
                db.ps.execute();

            }
JOptionPane.showMessageDialog(null, "table Exported to Postgres Database Server");

        } catch (Exception e) {
           JOptionPane.showMessageDialog(rootPane, "Data not Export \nTable probably exist\nTry a new name");
            e.printStackTrace();
        }

    }
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    public static javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void setcombo() {
        try {
            combomodel = new DefaultComboBoxModel();
            combomodel.addElement("------");
            combomodel.addElement("Mysql");
            combomodel.addElement("Psql");
            jComboBox2.setModel(combomodel);
            combomodel = new DefaultComboBoxModel();
            combomodel.addElement("------");
            Object report = "Name";
            for (int i = 0; i < Dababase_variable.DbEngineName.size(); i++) {
                combomodel.addElement(Dababase_variable.DbEngineName.elementAt(i));
            }

            jComboBox1.setModel(combomodel);

        } catch (Exception e) {
        }
    }
}
